- name: variables from play level
  hosts: localhost
  vars_files:
  - vars.yaml
  vars:  
     person: "gireesh from play"
     wishes: "morning from play"
  tasks:
  - name: check variables
    vars:
      person: "gireesh from task"
      wishes: "morning from task"
    ansible.builtin.debug:
      msg: "Hello {{person}}, good {{wishes}}"