- name: checking data types
  hosts: localhost
  vars:
    Name: gireesh #key value
    skills: #list type
    - Devops
    - Shell
    - Ansible
    - Linux
    Experience: #map type
      Devops: 7
      AWS: 6
      Docker: 4
    Trainer: true #boolean type
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
     msg: "name: {{Name}}"

  - name: print list
    ansible.builtin.debug:
     msg: "skills: {{skills}}"

  - name: print map
    ansible.builtin.debug:
     msg: "Experience: {{Experience}}"

  - name: print boolean
    ansible.builtin.debug:
     msg: "is he trainer: {{trainer}}"